[profile.default]
src = "src"
out = "out"
libs = ["lib"]
optimizer = true
optimizer-runs = 1000
solc-version = "0.8.24"

remappings = [
    "@openzeppelin/contracts@5.1.0/=lib/openzeppelin-contracts/contracts/"
]

# See more config options https://github.com/foundry-rs/foundry/blob/master/crates/config/README.md#all-options
